
def build(bld):
#    bld.program(install_path='${PREFIX}/tests', features='test', 
#            target='shooting_test', 
#            source='shooting_test.cpp', 
#            use='EIGEN')

    bld.program(install_path='${PREFIX}/tests', features='test', 
            target='lanczos_test1', 
            source='lanczos_test1.cpp', 
            use='matdec')

    bld.program(install_path='${PREFIX}/tests', features='test', 
            target='lanczos_test2', 
            source='lanczos_test2.cpp', 
            use='matdec')
    
    bld.program(install_path='${PREFIX}/tests', features='test', 
            target='lanczos_test3', 
            source='lanczos_test3.cpp', 
            use='matdec')
    
    bld.program(install_path='${PREFIX}/tests', features='test', 
            target='lanczos_test4', 
            source='lanczos_test4.cpp', 
            use='matdec')
