
def build(bld):
#    bld.shlib(target = 'pcor',
#            source = 'pcor.cpp',
#            use='EIGEN',
#            export_includes = ['.'])
    bld.shlib(target = 'matdec',
            source = 'matrix_decomps.cpp',
            use='EIGEN',
            export_includes = ['.'])
